import { expect, test, MM, drag, open, pixels, screen } from './util'

/** Height in mm of `n` lines of 12 pt text as the H field shows it. */
const lines = (n: number) => String(Math.round(((n * 16.452) / MM) * 100) / 100)

test('a new text is edited in its frame: typing, arrows, backspace, enter, escape and undo', async ({ page }) => {
  await open(page)
  const layers = page.getByRole('tree', { name: 'Layers' })
  const panel = page.getByRole('complementary', { name: 'Properties' })
  const height = panel.getByRole('textbox', { name: 'H in mm' })
  await page.keyboard.press('t')
  await page.mouse.click(...(await screen(page, 20, 80)))
  await expect(page.getByRole('textbox', { name: 'Text editor' })).toBeFocused()
  await page.keyboard.type('Hello')
  await expect(layers.getByRole('button', { name: 'Hello', exact: true })).toBeVisible()

  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('Backspace')
  await page.keyboard.type('L')
  await page.keyboard.press('End')
  await page.keyboard.press('Enter')
  await page.keyboard.type('World')
  await expect(layers.getByRole('button', { name: 'HeLlo World', exact: true })).toBeVisible()
  await expect(height).toHaveValue(lines(2))

  await page.keyboard.press('Control+a')
  const [x, y] = await screen(page, 20, 80)
  const shot = await pixels(page, x, y, 60, 30)
  expect(shot.some(([r, g, b]) => b > 230 && r > 150 && r < 225 && g > 200)).toBe(true)

  await page.keyboard.press('Escape')
  await expect(page.getByRole('textbox', { name: 'Text editor' })).toHaveCount(0)
  await expect(panel.getByRole('heading', { level: 2 })).toHaveText('HeLlo World')
  await page.keyboard.press('Control+z')
  await expect(layers.getByRole('button', { name: 'HeLlo', exact: true })).toBeVisible()
  await expect(height).toHaveValue(lines(1))
  await page.keyboard.press('Control+z')
  await expect(layers.getByRole('button', { name: 'Hello', exact: true })).toBeVisible()
})

test('double-clicking a text puts the caret where it was clicked, and ime input and paste insert there', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await open(page)
  const layers = page.getByRole('tree', { name: 'Layers' })
  await layers.getByRole('button', { name: /^Satz sets type/ }).click()
  await page.mouse.dblclick(...(await screen(page, 16, 97)))
  const editor = page.getByRole('textbox', { name: 'Text editor' })
  await expect(editor).toBeFocused()
  await page.keyboard.type('X')
  await expect(layers.getByRole('button', { name: /^XSatz sets type/ })).toBeVisible()

  const cdp = await context.newCDPSession(page)
  await cdp.send('Input.imeSetComposition', { text: '´', selectionStart: 1, selectionEnd: 1 })
  await cdp.send('Input.insertText', { text: 'é' })
  await expect(layers.getByRole('button', { name: /^XéSatz sets type/ })).toBeVisible()

  await page.keyboard.press('Shift+ArrowLeft')
  await page.keyboard.press('Shift+ArrowLeft')
  await page.keyboard.press('Control+c')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('Control+v')
  await expect(layers.getByRole('button', { name: /^XéXéSatz sets type/ })).toBeVisible()

  await page.mouse.click(...(await screen(page, 140, 205)))
  await expect(editor).toHaveCount(0)
})

test('copied layers paste back, text from outside pastes as a text layer and a moved duplicate repeats its step', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await open(page)
  const layers = page.getByRole('tree', { name: 'Layers' })
  const suns = layers.getByRole('button', { name: 'Sun', exact: true })
  await suns.click()
  await page.keyboard.press('Control+c')
  await page.keyboard.press('Control+v')
  await expect(suns).toHaveCount(2)

  await page.evaluate(() => navigator.clipboard.writeText('Hello from elsewhere'))
  await page.keyboard.press('Control+v')
  await expect(layers.getByRole('button', { name: 'Hello from elsewhere', exact: true })).toBeVisible()
  await page.evaluate(() => navigator.clipboard.writeText('Replaced'))
  await page.keyboard.press('Control+v')
  await expect(layers.getByRole('button', { name: 'Replaced', exact: true })).toHaveCount(1)
  await expect(layers.getByRole('button', { name: 'Hello from elsewhere', exact: true })).toHaveCount(0)

  await suns.first().click()
  const x = page.getByRole('complementary', { name: 'Properties' }).getByRole('textbox', { name: 'X in mm' }).first()
  const at = Number(await x.inputValue())
  await page.keyboard.press('Control+d')
  await page.keyboard.press('Shift+ArrowRight')
  await expect.poll(async () => Number(await x.inputValue())).toBeCloseTo(at + 1)
  await page.keyboard.press('Control+d')
  await expect.poll(async () => Number(await x.inputValue())).toBeCloseTo(at + 2)
  await expect(suns).toHaveCount(4)
})

test('a triple click in a text selects all of it', async ({ page }) => {
  await open(page)
  const layers = page.getByRole('tree', { name: 'Layers' })
  await layers.getByRole('button', { name: /^Satz sets type/ }).click()
  const at = await screen(page, 60, 100)
  await page.mouse.click(...at, { clickCount: 3 })
  await expect(page.getByRole('textbox', { name: 'Text editor' })).toBeFocused()
  await page.keyboard.type('Z')
  await expect(layers.getByRole('button', { name: 'Z', exact: true })).toBeVisible()
})

test('a paste away from the copied layers centres them under the pointer', async ({ page }) => {
  await open(page)
  const layout = page.getByRole('complementary', { name: 'Properties' }).getByRole('region', { name: 'Layout' })
  const field = (name: string) => layout.getByRole('textbox', { name: `${name} in mm` })
  await page.keyboard.press('r')
  await drag(page, await screen(page, 20, 20), await screen(page, 40, 30))
  await page.keyboard.press('Control+c')
  await page.mouse.move(...(await screen(page, 30, 25)))
  await page.keyboard.press('Control+v')
  await expect(field('X')).toHaveValue('20')
  await page.mouse.move(...(await screen(page, 100, 150)))
  await page.keyboard.press('Control+v')
  await expect(field('X')).toHaveValue('90')
  await expect(field('Y')).toHaveValue('145')
})

test('a double click that drags selects by character, not by word', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await open(page)
  await page.getByRole('tree', { name: 'Layers' }).getByRole('button', { name: /^Satz sets type/ }).click()
  const at = await screen(page, 69, 100)
  await page.mouse.dblclick(...at)
  await page.mouse.dblclick(...at)
  await page.keyboard.press('Control+c')
  const word = await page.evaluate(() => navigator.clipboard.readText())
  await page.mouse.click(...at)
  await page.mouse.down()
  await page.mouse.up()
  await page.mouse.down({ clickCount: 2 })
  await page.mouse.move(at[0] + 10, at[1], { steps: 3 })
  await page.mouse.up({ clickCount: 2 })
  await page.keyboard.press('Control+c')
  const part = await page.evaluate(() => navigator.clipboard.readText())
  expect(word).toContain(part)
  expect(part.length).toBeGreaterThan(0)
  expect(part.length).toBeLessThan(word.length)
})

test('a right click selects the layer under it and offers the actions for it', async ({ page }) => {
  await open(page)
  const layers = page.getByRole('tree', { name: 'Layers' })
  const rects = layers.getByRole('button', { name: 'Rectangle', exact: true })
  const menu = page.getByRole('menu', { name: 'Actions' })
  const before = await rects.count()
  await page.keyboard.press('r')
  await drag(page, await screen(page, 20, 20), await screen(page, 40, 40))
  await page.keyboard.press('Escape')
  await page.keyboard.press('v')
  await page.mouse.click(...(await screen(page, 5, 150)))
  await page.mouse.click(...(await screen(page, 30, 30)), { button: 'right' })
  await expect(layers.getByRole('treeitem', { selected: true })).toHaveCount(1)
  await expect(menu.getByRole('menuitem', { name: /Ungroup/ })).toBeDisabled()
  await menu.getByRole('menuitem', { name: /Duplicate/ }).click()
  await expect(menu).toHaveCount(0)
  await expect(rects).toHaveCount(before + 2)
  await rects.first().click({ button: 'right' })
  await expect(menu.getByRole('menuitem', { name: /Delete/ })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('toolbar', { name: 'Tools' }).click({ button: 'right' })
  await expect(menu.getByRole('menuitem', { name: /Select all/ })).toBeVisible()
  await expect(layers.getByRole('treeitem', { selected: true })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await page.mouse.click(...(await screen(page, 5, 150)), { button: 'right' })
  await expect(menu.getByRole('menuitem', { name: /Select all/ })).toBeVisible()
  const ruler = async () => (await page.locator('.ruler-x').boundingBox())?.height ?? 0
  expect(await ruler()).toBeGreaterThan(0)
  await menu.getByRole('menuitem', { name: /Show or hide rulers/ }).click()
  await expect.poll(ruler).toBe(0)
  await page.keyboard.press('Shift+R')
  await expect.poll(ruler).toBeGreaterThan(0)
})

test('enter edits the points of a shape, moving, adding and deleting them', async ({ page }) => {
  await open(page)
  const props = page.getByRole('complementary', { name: 'Properties' })
  const tools = page.getByRole('toolbar', { name: 'Path tools' })
  await page.keyboard.press('r')
  await drag(page, await screen(page, 20, 20), await screen(page, 60, 60))
  await page.keyboard.press('Enter')
  await expect(tools.getByRole('button', { name: 'Move point' })).toHaveAttribute('aria-pressed', 'true')
  await drag(page, await screen(page, 60, 60), await screen(page, 80, 60))
  await expect(props.getByRole('textbox', { name: 'W' })).toHaveValue('60')

  await page.keyboard.press('p')
  await expect(tools.getByRole('button', { name: 'Add point' })).toHaveAttribute('aria-pressed', 'true')
  await page.mouse.click(...(await screen(page, 40, 20)))
  await drag(page, await screen(page, 40, 20), await screen(page, 40, 10))
  await expect(props.getByRole('textbox', { name: 'H' })).toHaveValue('50')

  await page.keyboard.press('Delete')
  await expect(props.getByRole('textbox', { name: 'H' })).toHaveValue('40')
  await tools.getByRole('button', { name: 'Delete point' }).click()
  await page.mouse.click(...(await screen(page, 80, 60)))
  await expect(props.getByRole('textbox', { name: 'W' })).toHaveValue('40')

  await page.keyboard.press('Enter')
  await expect(tools).toHaveCount(0)
  await expect(page.getByRole('toolbar', { name: 'Tools' })).toBeVisible()
})

test('ctrl click and the path tools make a point smooth or a corner', async ({ page }) => {
  await open(page)
  const w = page.getByRole('complementary', { name: 'Properties' }).getByRole('textbox', { name: 'W' })
  const tools = page.getByRole('toolbar', { name: 'Path tools' })
  await page.keyboard.press('r')
  await drag(page, await screen(page, 20, 20), await screen(page, 60, 60))
  await page.keyboard.press('Enter')
  await expect(tools.getByRole('button', { name: 'Smooth point' })).toBeDisabled()
  await page.keyboard.down('Control')
  await page.mouse.click(...(await screen(page, 60, 20)))
  await expect(w).not.toHaveValue('40')
  await page.mouse.click(...(await screen(page, 60, 20)))
  await expect(w).toHaveValue('40')
  await page.keyboard.up('Control')
  await page.mouse.click(...(await screen(page, 60, 20)))
  await tools.getByRole('button', { name: 'Smooth point' }).click()
  await expect(w).not.toHaveValue('40')
  await tools.getByRole('button', { name: 'Corner point' }).click()
  await expect(w).toHaveValue('40')
})

test('a layer turns by its corner and is hit where it shows', async ({ page }) => {
  await open(page)
  const props = page.getByRole('complementary', { name: 'Properties' })
  await page.keyboard.press('r')
  await drag(page, await screen(page, 20, 20), await screen(page, 60, 40))
  const [x, y] = await screen(page, 60, 20)
  const [cx, cy] = await screen(page, 40, 30)
  const from = [x + 8, y - 8] as const
  await page.mouse.move(...from)
  await expect(page.getByLabel('Page canvas')).toHaveCSS('cursor', /url/)
  await page.keyboard.down('Shift')
  await drag(page, from, [cx + (from[1] - cy), cy - (from[0] - cx)])
  await page.keyboard.up('Shift')
  await expect(props.getByRole('textbox', { name: 'Rotation in °' })).toHaveValue('90')

  await page.keyboard.press('Escape')
  await expect(props.getByRole('textbox', { name: 'Rotation in °' })).toHaveCount(0)
  await page.mouse.click(...(await screen(page, 40, 48)))
  await expect(props.getByRole('textbox', { name: 'Rotation in °' })).toHaveValue('90')
  const field = props.getByRole('textbox', { name: 'Rotation in °' })
  await field.fill('-45')
  await field.press('Enter')
  await expect(field).toHaveValue('315')
  await props.getByTitle('Rotation in °').locator('.field-label').dblclick()
  await expect(field).toHaveValue('0')
})
