import { expect, test, open } from './util'

test('find steps through the matches in every story and replaces them in 1 undo step', async ({ page }) => {
  await open(page)
  await page.keyboard.press('Control+f')
  const find = page.getByRole('dialog', { name: 'Find and replace' })
  await find.getByRole('textbox', { name: 'Find' }).fill('The')
  await expect(find.getByText('9 found')).toBeVisible()
  await find.getByRole('checkbox', { name: 'Case' }).check()
  await expect(find.getByText('2 found')).toBeVisible()
  await find.getByRole('textbox', { name: 'Find' }).press('Enter')
  await expect(find.getByText('1 of 2')).toBeVisible()
  await find.getByRole('button', { name: 'Next match' }).click()
  await expect(find.getByText('2 of 2')).toBeVisible()
  await find.getByRole('textbox', { name: 'Replace with' }).fill('A')
  await find.getByRole('button', { name: 'All' }).click()
  await expect(page.getByText('Replaced 2 matches')).toBeVisible()
  await expect(find.getByText('0 found')).toBeVisible()
  const layers = page.getByRole('tree', { name: 'Layers' })
  await expect(layers.getByRole('button', { name: /^Satz sets type in the browser\. A engine/ })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(find).toHaveCount(0)
  await page.keyboard.press('Escape')
  await page.keyboard.press('Control+z')
  await expect(layers.getByRole('button', { name: /^Satz sets type in the browser\. The/ })).toBeVisible()
})
