import { expect, test } from '@playwright/test'
import { open } from './util'

test('the layers tree is one tab stop whose arrow keys move, open and close', async ({ page }) => {
  await open(page)
  const layers = page.getByRole('tree', { name: 'Layers' })
  const names = layers.locator('.layer-name')
  const group = layers.getByRole('treeitem').first()
  await expect(names.nth(0)).toHaveText('Shapes')
  await expect(names.nth(0)).toHaveAttribute('tabindex', '0')
  await expect(names.nth(1)).toHaveAttribute('tabindex', '-1')

  await names.nth(0).focus()
  await page.keyboard.press('ArrowDown')
  await expect(names.nth(1)).toBeFocused()
  await page.keyboard.press('ArrowUp')
  await expect(names.nth(0)).toBeFocused()
  await expect(group).toHaveAttribute('aria-expanded', 'true')
  await page.keyboard.press('ArrowLeft')
  await expect(group).toHaveAttribute('aria-expanded', 'false')
  await page.keyboard.press('ArrowRight')
  await expect(group).toHaveAttribute('aria-expanded', 'true')
  await page.keyboard.press('ArrowRight')
  await expect(names.nth(1)).toBeFocused()
  await page.keyboard.press('ArrowLeft')
  await expect(layers.getByRole('treeitem', { level: 2 }).first()).toHaveAttribute('aria-expanded', 'false')
  await page.keyboard.press('ArrowLeft')
  await expect(names.nth(0)).toBeFocused()

  await page.keyboard.press('Enter')
  await expect(group).toHaveAttribute('aria-selected', 'true')
  await page.keyboard.press('Tab')
  await expect(layers.locator(':focus')).toHaveCount(0)
})

test('the pages list is one tab stop; arrows move through it and Alt with an arrow moves the page', async ({ page }) => {
  await open(page)
  const pages = page.getByRole('navigation', { name: 'Pages' })
  const row = (n: number) => pages.getByRole('button', { name: `Page ${n}`, exact: true })
  await pages.getByRole('button', { name: 'Add page' }).click()
  await pages.getByRole('button', { name: 'Add page' }).click()
  await expect(row(3)).toHaveAttribute('tabindex', '0')
  await expect(row(1)).toHaveAttribute('tabindex', '-1')

  await row(1).click()
  await page.keyboard.press('ArrowDown')
  await expect(row(2)).toBeFocused()
  await page.keyboard.press('ArrowLeft')
  await expect(row(1)).toBeFocused()
  await page.keyboard.press('ArrowRight')
  await expect(row(2)).toBeFocused()

  await row(1).click()
  await page.keyboard.press('Alt+ArrowDown')
  await expect(row(2)).toHaveAttribute('aria-current', 'page')
  await expect(row(2)).toBeFocused()
  await page.keyboard.press('Alt+ArrowRight')
  await expect(row(3)).toHaveAttribute('aria-current', 'page')
  await page.keyboard.press('Alt+ArrowUp')
  await expect(row(2)).toHaveAttribute('aria-current', 'page')
  await expect(row(2)).toBeFocused()
})

test('the arrow keys move through a context menu', async ({ page }) => {
  await open(page)
  const pages = page.getByRole('navigation', { name: 'Pages' })
  await pages.getByRole('button', { name: 'Add page' }).click()
  await pages.getByRole('button', { name: 'Page 1', exact: true }).click({ button: 'right' })
  const item = (name: string) => page.getByRole('menuitem', { name })
  await expect(item('Duplicate page')).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(item('Delete page')).toBeFocused()
  await page.keyboard.press('ArrowUp')
  await expect(item('Duplicate page')).toBeFocused()
})
