import { expect, test } from '@playwright/test'
import { drag, open, pixels, screen } from './util'

test('a master is made, applied to a page, overridden with ctrl+shift+click and reset', async ({ page }) => {
  await open(page)
  const pages = page.getByRole('navigation', { name: 'Pages' })
  const layers = page.getByRole('tree', { name: 'Layers' })
  const panel = page.getByRole('complementary', { name: 'Properties' })
  const title = panel.getByRole('heading', { level: 2 })
  const rects = layers.getByRole('button', { name: 'Rectangle', exact: true })

  await pages.getByRole('button', { name: 'Add master' }).click()
  const master = pages.getByRole('button', { name: 'A-Master', exact: true })
  await expect(master).toHaveAttribute('aria-current', 'page')
  await expect(layers.getByRole('treeitem')).toHaveCount(0)
  await page.keyboard.press('r')
  await drag(page, await screen(page, 20, 197), await screen(page, 60, 207))
  await expect(rects).toHaveCount(1)
  await master.dblclick()
  await pages.getByRole('textbox', { name: 'Master name' }).fill('Body')
  await pages.getByRole('textbox', { name: 'Master name' }).press('Enter')
  await expect(pages.getByRole('button', { name: 'Body', exact: true })).toBeVisible()

  await pages.getByRole('button', { name: 'Page 1', exact: true }).click()
  await expect(rects).toHaveCount(2)
  await panel.getByRole('combobox', { name: 'Master' }).selectOption('Body')
  await expect(pages.getByRole('listitem').filter({ hasText: 'Page 1' })).toContainText('B')
  await page.mouse.move(1, 1)
  const at = await screen(page, 40, 202)
  const [gray] = await pixels(page, at[0], at[1], 1, 1)
  expect(gray.every((c) => Math.abs(c - 0xd9) < 8)).toBe(true)

  await page.mouse.click(...at)
  await expect(title).toHaveText('Page')
  await page.keyboard.down('Control')
  await page.keyboard.down('Shift')
  await page.mouse.click(...at)
  await page.keyboard.up('Shift')
  await page.keyboard.up('Control')
  await expect(rects).toHaveCount(3)
  await expect(title).toHaveText('Rectangle')
  await panel.getByRole('button', { name: 'Reset to master' }).click()
  await expect(rects).toHaveCount(2)
  await expect(title).toHaveText('Page')
  await page.keyboard.press('Control+z')
  await expect(rects).toHaveCount(3)
})
