import { expect, test, addPage, colors, current, drag, open, option, overview, screen, showPage } from './util'

test('pages are added, shown, reordered, duplicated and deleted with undo', async ({ page }) => {
  await open(page)
  const layers = page.getByRole('tree', { name: 'Layers' })
  const row = (n: number) => option(page, n)
  const rects = layers.getByRole('button', { name: 'Rectangle', exact: true })
  await expect(current(page, 1)).toHaveAttribute('aria-pressed', 'true')
  await expect(rects).toHaveCount(2)

  await addPage(page)
  await expect(current(page, 2)).toHaveAttribute('aria-pressed', 'true')
  await expect(layers.getByRole('treeitem')).toHaveCount(0)
  await page.keyboard.press('r')
  await drag(page, await screen(page, 20, 20), await screen(page, 60, 50))
  await expect(rects).toHaveCount(1)

  await showPage(page, 1)
  await expect(rects).toHaveCount(2)
  await overview(page)
  await row(2).dragTo(row(1), { targetPosition: { x: 20, y: 2 } })
  await expect(row(2)).toHaveAttribute('aria-current', 'page')
  await showPage(page, 1)
  await expect(rects).toHaveCount(1)
  await page.keyboard.press('Control+z')
  await expect(current(page, 2)).toHaveAttribute('aria-pressed', 'true')
  await showPage(page, 1)
  await expect(rects).toHaveCount(2)

  await overview(page)
  await row(1).click({ button: 'right' })
  await page.getByRole('menuitem', { name: 'Duplicate page' }).click()
  await expect(row(3)).toBeVisible()
  await expect(row(2)).toHaveAttribute('aria-current', 'page')
  await page.keyboard.press('.')
  await expect(rects).toHaveCount(2)
  await overview(page)
  await row(3).click({ button: 'right' })
  await page.getByRole('menuitem', { name: 'Delete page' }).click()
  await expect(row(3)).toHaveCount(0)
  await expect(row(2)).toHaveAttribute('aria-current', 'page')
  await page.keyboard.press('Control+z')
  await expect(row(3)).toBeVisible()
})

test('the page size is set per page in the properties panel', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  const width = panel.getByRole('textbox', { name: 'W in mm' })
  await addPage(page)
  await width.fill('420')
  await width.press('Enter')
  await panel.getByRole('textbox', { name: 'H in mm' }).fill('594')
  await panel.getByRole('textbox', { name: 'H in mm' }).press('Enter')
  await expect(width).toHaveValue('420')
  await showPage(page, 1)
  await expect(width).toHaveValue('148')
})

test('with facing pages the page overview shows spreads from a first right page, without them single pages', async ({ page }) => {
  await open(page)
  const row = (n: number) => option(page, n)
  const facing = page.getByRole('complementary', { name: 'Properties' }).getByRole('checkbox', { name: 'Facing pages' })
  for (let i = 0; i < 3; i++) await addPage(page)
  await showPage(page, 1)
  await expect(facing).toBeChecked()
  const pages = await overview(page)
  const spread = (name: string) => pages.getByRole('group', { name, exact: true })
  const names = (name: string) => spread(name).getByRole('option').evaluateAll((es) => es.map((e) => e.getAttribute('aria-label')))
  expect(await names('Spread 1')).toEqual(['Page 1'])
  expect(await names('Spread 2–3')).toEqual(['Page 2', 'Page 3'])
  expect(await names('Spread 4')).toEqual(['Page 4'])
  const [one, two, three] = await Promise.all([1, 2, 3].map(async (n) => (await row(n).boundingBox())!))
  expect(three.x).toBeGreaterThan(two.x)
  expect(Math.abs(one.x - three.x)).toBeLessThan(1)

  await facing.uncheck()
  await expect(pages.getByRole('group', { name: /^Spread/ })).toHaveCount(0)
  await expect(row(4)).toBeVisible()
  await page.keyboard.press('Control+z')
  await expect(facing).toBeChecked()
  await expect(spread('Spread 2–3')).toBeVisible()
})

test('layout grids show on the page, hide with shift g and apply to all pages', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  const count = panel.getByRole('textbox', { name: 'Columns' })
  const at = async (x: number, y: number) => (await colors(page, [await screen(page, x, y)]))[0]
  await addPage(page)
  await panel.getByRole('button', { name: 'Add layout grid' }).click()
  await expect(count).toHaveValue('2')
  await expect.poll(() => at(40, 100)).not.toEqual([255, 255, 255])
  expect(await at(5, 100)).toEqual([255, 255, 255])
  expect(await at(73, 100)).toEqual([255, 255, 255])
  await page.keyboard.press('Shift+G')
  await expect.poll(() => at(40, 100)).toEqual([255, 255, 255])
  await page.keyboard.press('Shift+G')
  await panel.getByRole('button', { name: 'Apply grids to all pages' }).click()
  await showPage(page, 1)
  await expect(count).toHaveValue('2')
  await panel.getByRole('button', { name: 'Remove grid' }).click()
  await expect(count).toHaveCount(0)
})
