import { expect, test } from '@playwright/test'
import { drag, open, screen } from './util'

test('pages are added, shown, reordered, duplicated and deleted with undo', async ({ page }) => {
  await open(page)
  const pages = page.getByRole('navigation', { name: 'Pages' })
  const layers = page.getByRole('tree', { name: 'Layers' })
  const row = (n: number) => pages.getByRole('button', { name: `Page ${n}`, exact: true })
  const rects = layers.getByRole('button', { name: 'Rectangle', exact: true })
  await expect(row(1)).toHaveAttribute('aria-current', 'page')
  await expect(rects).toHaveCount(2)

  await pages.getByRole('button', { name: 'Add page' }).click()
  await expect(row(2)).toHaveAttribute('aria-current', 'page')
  await expect(layers.getByRole('treeitem')).toHaveCount(0)
  await page.keyboard.press('r')
  await drag(page, await screen(page, 20, 20), await screen(page, 60, 50))
  await expect(rects).toHaveCount(1)

  await row(1).click()
  await expect(rects).toHaveCount(2)
  await row(2).dragTo(row(1), { targetPosition: { x: 20, y: 2 } })
  await expect(row(2)).toHaveAttribute('aria-current', 'page')
  await row(1).click()
  await expect(rects).toHaveCount(1)
  await page.keyboard.press('Control+z')
  await expect(row(2)).toHaveAttribute('aria-current', 'page')
  await row(1).click()
  await expect(rects).toHaveCount(2)

  await row(1).click({ button: 'right' })
  await page.getByRole('menuitem', { name: 'Duplicate page' }).click()
  await expect(row(3)).toBeVisible()
  await expect(row(2)).toHaveAttribute('aria-current', 'page')
  await expect(rects).toHaveCount(2)
  await row(3).click({ button: 'right' })
  await page.getByRole('menuitem', { name: 'Delete page' }).click()
  await expect(row(3)).toHaveCount(0)
  await expect(row(2)).toHaveAttribute('aria-current', 'page')
  await page.keyboard.press('Control+z')
  await expect(row(3)).toBeVisible()
})

test('the page size is set per page in the properties panel', async ({ page }) => {
  await open(page)
  const pages = page.getByRole('navigation', { name: 'Pages' })
  const panel = page.getByRole('complementary', { name: 'Properties' })
  const width = panel.getByRole('textbox', { name: 'W in mm' })
  await pages.getByRole('button', { name: 'Add page' }).click()
  await width.fill('420')
  await width.press('Enter')
  await panel.getByRole('textbox', { name: 'H in mm' }).fill('594')
  await panel.getByRole('textbox', { name: 'H in mm' }).press('Enter')
  await expect(width).toHaveValue('420')
  await pages.getByRole('button', { name: 'Page 1', exact: true }).click()
  await expect(width).toHaveValue('148')
})
