import { expect, test } from '@playwright/test'
import { addMaster, addPage, open, option, overview } from './util'

test('a closed section stays closed for other selections', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  const layers = page.getByRole('tree', { name: 'Layers' })
  const toggle = panel.getByRole('button', { name: 'Layout' })
  await layers.getByRole('button', { name: 'Sun' }).click()
  await expect(panel.getByRole('heading', { level: 2 })).toHaveText('Sun')
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await expect(panel.getByRole('region', { name: 'Layout' }).locator('.section-body')).toHaveAttribute('inert')
  await layers.getByRole('button', { name: 'Rectangle', exact: true }).first().click()
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await toggle.click()
  await expect(panel.getByRole('region', { name: 'Layout' }).locator('.section-body')).not.toHaveAttribute('inert')
})

test('the document section sets the format, orientation and page count of all pages', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  const document = panel.getByRole('region', { name: 'Document' })
  const width = document.getByRole('textbox', { name: 'Width of all pages in mm' })
  await addPage(page)
  await expect(document.getByRole('combobox', { name: 'Format' })).toHaveValue('A5')
  await document.getByRole('combobox', { name: 'Format' }).selectOption('A4')
  await expect(width).toHaveValue('210')
  await document.getByRole('radio', { name: 'Landscape' }).click()
  await expect(width).toHaveValue('297')
  await expect(panel.getByRole('region', { name: 'Page 2' }).getByRole('textbox', { name: 'W in mm' })).toHaveValue('297')

  const pages = document.getByRole('textbox', { name: 'Pages', exact: true })
  await expect(pages).toHaveValue('2')
  await document.getByRole('button', { name: 'Increase Pages' }).click()
  await expect(pages).toHaveValue('3')
  await pages.fill('1')
  await pages.press('Enter')
  await expect(pages).toHaveValue('1')
  await page.keyboard.press('Control+z')
  await expect(pages).toHaveValue('3')
})

test('the master select sets the master of the pages selected in the overview and shows mixed', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  const master = panel.getByRole('combobox', { name: 'Master' })
  await addMaster(page)
  await addPage(page)
  await overview(page)
  await option(page, 2).click()
  await master.selectOption('A-Master')
  await option(page, 1).click({ modifiers: ['Shift'] })
  await expect(panel.getByRole('region', { name: 'Pages 1, 2' })).toBeVisible()
  await expect(master.locator('option:checked')).toHaveText('Mixed')
  await master.selectOption('A-Master')
  await expect(master).toHaveValue(/./)
  await expect(master.locator('option:checked')).toHaveText('A-Master')
})

test('the text style specimen opens a menu of the styles set at their size', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  await page.getByRole('tree', { name: 'Layers' }).getByRole('button', { name: /^Satz sets type/ }).click()
  await panel.getByRole('button', { name: 'Create text style' }).click()
  const specimen = panel.getByTitle('Text style', { exact: true })
  await expect(specimen).toContainText('Text style 1')
  await specimen.click()
  await expect(page.getByRole('menuitemradio', { name: 'Text style 1' })).toBeFocused()
  await page.getByRole('menuitemradio', { name: 'No style' }).click()
  await expect(specimen).toContainText('No style')
})
