import { expect, test, addMaster, addPage, open, option, overview, choose } from './util'

test('the page section sets the format and orientation, the document section the page count', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  const document = panel.getByRole('region', { name: 'Document' })
  await addPage(page)
  const sheet = panel.getByRole('region', { name: 'Page 2' })
  const width = sheet.getByRole('textbox', { name: 'W in mm' })
  await expect(sheet.getByRole('combobox', { name: 'Format' })).toHaveText('A5')
  const zoom = await page.getByLabel('Zoom').textContent()
  await choose(sheet.getByRole('combobox', { name: 'Format' }), 'A4')
  await expect(width).toHaveValue('210')
  await expect(page.getByLabel('Zoom')).not.toHaveText(zoom!)
  await sheet.getByRole('radio', { name: 'Landscape' }).click()
  await expect(width).toHaveValue('297')

  const pages = document.getByRole('textbox', { name: 'Pages', exact: true })
  await expect(pages).toHaveValue('2')
  await document.getByRole('button', { name: 'Increase Pages' }).click()
  await expect(pages).toHaveValue('3')
  await pages.fill('1')
  await pages.press('Enter')
  await expect(pages).toHaveValue('1')
  await page.keyboard.press('Control+z')
  await expect(pages).toHaveValue('3')
})

test('the master select sets the master of the pages selected in the overview and shows mixed', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  const master = panel.getByRole('combobox', { name: 'Master' })
  await addMaster(page)
  await addPage(page)
  await overview(page)
  await choose(master, 'A-Master')
  await option(page, 1).click({ modifiers: ['Shift'] })
  await expect(panel.getByRole('region', { name: 'Pages 1, 2' })).toBeVisible()
  await expect(master).toHaveText('Mixed')
  await choose(master, 'A-Master')
  await expect(master).toHaveText('A-Master')
})

test('the text style specimen opens a menu of the styles set at their size, marks overrides and resets or updates the style', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  await page.getByRole('tree', { name: 'Layers' }).getByRole('button', { name: /^Satz sets type/ }).click()
  await panel.getByRole('button', { name: 'Create text style' }).click()
  await page.mouse.move(0, 0)
  const specimen = panel.getByTitle('Text style', { exact: true })
  await expect(specimen).toContainText('Text style 1')
  await specimen.click()
  await expect(page.getByRole('menuitemradio', { name: 'Text style 1' })).toBeFocused()
  await page.keyboard.press('Escape')
  const size = panel.getByRole('textbox', { name: 'Font size in pt' }).first()
  await size.fill('30')
  await size.press('Enter')
  await expect(specimen).toContainText('Text style 1*')
  await specimen.click()
  await page.getByRole('menuitem', { name: 'Reset to style' }).click()
  await expect(specimen).not.toContainText('*')
  await size.fill('30')
  await size.press('Enter')
  await specimen.click()
  await page.getByRole('menuitem', { name: 'Update style' }).click()
  await expect(specimen).toContainText('30/')
  await expect(specimen).not.toContainText('*')
  await specimen.click()
  await page.getByRole('menuitemradio', { name: 'No style' }).click()
  await expect(specimen).toContainText('No style')
})

test('a fill is dragged below another to reorder them', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  await page.getByRole('tree', { name: 'Layers' }).getByRole('button', { name: 'Rectangle', exact: true }).last().click()
  const fills = panel.getByRole('region', { name: 'Fill' })
  await fills.getByRole('button', { name: 'Add fill' }).click()
  const types = fills.getByRole('combobox', { name: 'Fill type' })
  await choose(types.first(), 'Linear')
  await expect(types).toHaveText(['Linear', 'Solid'])
  await fills.getByRole('listitem').first().dragTo(fills.getByRole('listitem').last())
  await expect(types).toHaveText(['Solid', 'Linear'])
})

test('properties the selected layers share are edited together', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  const layers = page.getByRole('tree', { name: 'Layers' })
  await layers.getByRole('button', { name: 'Sun', exact: true }).click()
  await layers.getByRole('button', { name: 'Triangle', exact: true }).click({ modifiers: ['Control'] })
  await panel.getByRole('textbox', { name: 'Opacity in %', exact: true }).fill('50')
  await panel.getByRole('textbox', { name: 'Opacity in %', exact: true }).press('Enter')
  const fill = panel.getByRole('region', { name: 'Fill' })
  await expect(fill).toContainText('Mixed — + replaces')
  await fill.getByRole('button', { name: 'Add fill' }).click()
  await expect(fill.getByRole('button', { name: 'Fill color' })).toHaveCount(1)
  for (const name of ['Sun', 'Triangle']) {
    await layers.getByRole('button', { name, exact: true }).click()
    await expect(panel.getByRole('textbox', { name: 'Opacity in %', exact: true })).toHaveValue('50')
    await expect(fill.getByRole('button', { name: 'Fill color' })).toHaveCount(1)
  }
})
