import { type Page } from '@playwright/test'
import { expect, test, addMaster, drag, open, screen } from './util'

const layout = (page: Page) => page.getByRole('complementary', { name: 'Properties' }).getByRole('region', { name: 'Layout' })
const value = async (page: Page, name: string) => Number(await layout(page).getByRole('textbox', { name: `${name} in mm` }).inputValue())
const labels = (page: Page) => page.locator('.marks text')

test('drawing and moving snap to the page and other layers unless ctrl is held', async ({ page }) => {
  await open(page)
  await addMaster(page)
  await page.keyboard.press('r')
  await drag(page, await screen(page, 1, 0.8), await screen(page, 40, 30))
  expect(await value(page, 'X')).toBe(0)
  expect(await value(page, 'Y')).toBe(0)
  await page.keyboard.press('r')
  await drag(page, await screen(page, 100, 100), await screen(page, 120, 120))

  await page.mouse.move(...(await screen(page, 20, 15)))
  await page.mouse.down()
  await page.mouse.move(...(await screen(page, 73.4, 15.3)), { steps: 6 })
  await expect(page.locator('.marks line')).not.toHaveCount(0)
  await expect(labels(page)).toHaveCount(2)
  await expect(labels(page).first()).toHaveText(/^\d+(\.\d)? mm$/)
  await page.mouse.up()
  await expect(labels(page)).toHaveCount(0)
  expect(await value(page, 'X')).toBe(54)
  expect(await value(page, 'Y')).toBe(0)

  await page.mouse.move(...(await screen(page, 74, 15)))
  await page.mouse.down()
  await page.keyboard.down('Control')
  await page.mouse.move(...(await screen(page, 80, 15)), { steps: 3 })
  await page.mouse.move(...(await screen(page, 75, 15)), { steps: 3 })
  await page.mouse.up()
  await page.keyboard.up('Control')
  expect(await value(page, 'X')).toBeCloseTo(55, 0)
  expect(await value(page, 'X')).not.toBe(54)
})

test('alt shows the distances to the layer under the pointer or to the page', async ({ page }) => {
  await open(page)
  await addMaster(page)
  await page.keyboard.press('r')
  await drag(page, await screen(page, 20, 20), await screen(page, 40, 40))
  await page.keyboard.press('r')
  await drag(page, await screen(page, 80, 20), await screen(page, 100, 40))
  await page.mouse.click(...(await screen(page, 30, 30)))

  await page.mouse.move(...(await screen(page, 60, 120)))
  await page.keyboard.down('Alt')
  await expect(labels(page)).toHaveText(['20 mm', '40 mm', '20 mm', '170 mm'])
  await page.mouse.move(...(await screen(page, 90, 30)))
  await expect(labels(page)).toHaveText(['40 mm'])
  await page.keyboard.up('Alt')
  await expect(labels(page)).toHaveCount(0)

  const bar = page.getByRole('toolbar', { name: 'Quick edit' })
  await bar.hover()
  await page.keyboard.down('Alt')
  await expect(bar).toBeVisible()
  await expect(labels(page)).toHaveCount(0)
  await page.keyboard.up('Alt')
})

test('distance labels never cover each other', async ({ page }) => {
  await open(page)
  await addMaster(page)
  for (const [x, y, w, h] of [[20, 50, 10, 2], [20, 53, 10, 2], [40, 50, 10, 5]]) {
    await page.keyboard.press('r')
    await page.keyboard.down('Control')
    await drag(page, await screen(page, x, y), await screen(page, x + w, y + h))
    await page.keyboard.up('Control')
  }
  await page.mouse.move(...(await screen(page, 45, 52)))
  await page.mouse.down()
  await page.mouse.move(...(await screen(page, 47, 52)), { steps: 3 })
  await expect(labels(page)).toHaveText(['12 mm', '12 mm'])
  const boxes = await page.locator('.marks rect.label').evaluateAll((rs) => rs.map((r) => r.getBoundingClientRect().toJSON() as DOMRect))
  for (const [i, a] of boxes.entries())
    for (const b of boxes.slice(i + 1)) expect(a.right <= b.left || b.right <= a.left || a.bottom <= b.top || b.bottom <= a.top).toBe(true)
  await page.mouse.up()
})
