import { expect, test, drag, open, pixels, screen, choose } from './util'

test('type attributes and a text style are set in the text section and edited on the page', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  const text = page.getByRole('tree', { name: 'Layers' }).getByRole('button', { name: /^Satz sets type/ })
  const field = (name: string) => panel.getByRole('textbox', { name })
  const commit = async (name: string, value: string) => {
    await field(name).fill(value)
    await field(name).press('Enter')
  }
  await text.click()
  await expect(field('Font size in pt')).toHaveValue('14')
  await expect(field('Line height in pt')).toHaveValue('Auto')
  await expect(panel.getByRole('radio', { name: 'Justify' })).toBeChecked()

  await commit('Font size in pt', '11')
  await commit('Line height in pt', '15')
  await panel.getByRole('radio', { name: 'Align center' }).click()
  await expect(panel.getByRole('radio', { name: 'Align center' })).toBeChecked()
  await panel.getByTitle('Text style', { exact: true }).click()
  await page.getByRole('menuitem', { name: 'Create text style' }).click()
  await page.mouse.move(0, 0)
  await expect(panel.getByTitle('Text style', { exact: true })).toContainText('Text style 1')

  await page.keyboard.press('Escape')
  const style = panel.getByRole('group', { name: 'Text style 1' })
  await expect(style.getByRole('textbox', { name: 'Font size in pt' })).toHaveValue('11')
  await style.getByRole('textbox', { name: 'Font size in pt' }).fill('9')
  await style.getByRole('textbox', { name: 'Font size in pt' }).press('Enter')
  await text.click()
  await expect(field('Font size in pt')).toHaveValue('9')
  await commit('Line height in pt', 'auto')
  await expect(field('Line height in pt')).toHaveValue('Auto')
  await expect(panel.getByTitle('Text style', { exact: true })).toContainText('No style')
  await expect(field('Font size in pt')).toHaveValue('9')
})

test('case, decoration, indent and OpenType features are set in the type options and kept by a text style', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  const text = page.getByRole('tree', { name: 'Layers' }).getByRole('button', { name: /^Satz sets type/ })
  await text.click()
  await panel.getByRole('button', { name: 'Type options' }).click()
  const options = page.getByRole('dialog', { name: 'Type options' })
  await choose(options.getByRole('combobox', { name: 'Case' }), 'Upper case')
  await choose(options.getByRole('combobox', { name: 'Decoration' }), 'Underline')
  await options.getByRole('textbox', { name: 'Paragraph indent in pt' }).fill('12')
  await options.getByRole('textbox', { name: 'Paragraph indent in pt' }).press('Enter')
  await options.getByRole('checkbox', { name: 'Ligatures', exact: true }).uncheck()
  await options.getByRole('checkbox', { name: 'Oldstyle figures' }).check()
  await page.screenshot({ path: 'test-results/type-options.png' })
  await page.keyboard.press('Escape')
  await expect(options).toHaveCount(0)

  await panel.getByTitle('Text style', { exact: true }).click()
  await page.getByRole('menuitem', { name: 'Create text style' }).click()
  await page.keyboard.press('Escape')
  await panel.getByRole('group', { name: 'Text style 1' }).getByRole('button', { name: 'Type options' }).click()
  await expect(options.getByRole('combobox', { name: 'Case' })).toHaveText('Upper case')
  await expect(options.getByRole('combobox', { name: 'Decoration' })).toHaveText('Underline')
  await expect(options.getByRole('textbox', { name: 'Paragraph indent in pt' })).toHaveValue('12')
  await expect(options.getByRole('checkbox', { name: 'Ligatures', exact: true })).not.toBeChecked()
  await expect(options.getByRole('checkbox', { name: 'Oldstyle figures' })).toBeChecked()
})

test('the insert character menu puts dashes and quotes into the edited text', async ({ page }) => {
  await open(page)
  await page.keyboard.press('t')
  await page.mouse.click(...(await screen(page, 10, 200, 0)))
  await page.keyboard.type('a')
  for (const name of ['En dash', 'Low quote']) {
    await page.getByRole('complementary', { name: 'Properties' }).getByRole('button', { name: 'Insert character' }).click()
    await page.getByRole('menuitem', { name }).click()
  }
  await page.keyboard.type('b')
  await expect(page.getByRole('tree', { name: 'Layers' }).getByRole('button', { name: 'a\u2013\u201eb', exact: true })).toBeVisible()
})

test('lorem with a count and tab types that many words of lorem ipsum', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await open(page)
  const layers = page.getByRole('tree', { name: 'Layers' })
  await page.keyboard.press('t')
  await page.mouse.click(...(await screen(page, 10, 200, 0)))
  await page.keyboard.type('Hi lorem3')
  await page.keyboard.press('Tab')
  await expect(layers.getByRole('button', { name: 'Hi Lorem ipsum dolor.', exact: true })).toBeVisible()
  await page.keyboard.type(' lorem')
  await page.keyboard.press('Tab')
  await page.keyboard.press('Control+a')
  await page.keyboard.press('Control+c')
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(
    'Hi Lorem ipsum dolor. Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.',
  )
})

test('hyphenation is switched per paragraph with its language', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  await page.getByRole('tree', { name: 'Layers' }).getByRole('button', { name: /^Satz sets type/ }).click()
  const hyphenate = panel.getByRole('checkbox', { name: 'Hyphenate' })
  const lang = panel.getByRole('combobox', { name: 'Hyphenation language' })
  await expect(hyphenate).toBeChecked()
  await expect(lang).toHaveText('English')
  await choose(lang, 'German')
  await expect(lang).toBeFocused()
  await hyphenate.uncheck()
  await page.keyboard.press('Control+z')
  await expect(hyphenate).toBeChecked()
  await expect(lang).toHaveText('German')
})

test('insets, columns, vertical alignment and baseline grid are set in the text frame section', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  await page.getByRole('tree', { name: 'Layers' }).getByRole('button', { name: /^Satz sets type/ }).click()
  const frame = panel.getByRole('region', { name: 'Text frame' })
  const field = (name: string) => frame.getByRole('textbox', { name })
  await expect(field('Columns')).toHaveValue('1')
  await expect(field('Baseline grid in pt')).toHaveValue('Off')
  for (const [name, value] of [['Top inset in mm', '2'], ['Columns', '2'], ['Gutter in mm', '5'], ['Baseline grid in pt', '18']]) {
    await field(name).fill(value)
    await field(name).press('Enter')
  }
  await frame.getByRole('radio', { name: 'Align bottom' }).click()
  await page.keyboard.press('Escape')
  await page.getByRole('tree', { name: 'Layers' }).getByRole('button', { name: /^Satz sets type/ }).click()
  await expect(field('Top inset in mm')).toHaveValue('2')
  await expect(field('Columns')).toHaveValue('2')
  await expect(field('Gutter in mm')).toHaveValue('5')
  await expect(field('Baseline grid in pt')).toHaveValue('18')
  await expect(frame.getByRole('radio', { name: 'Align bottom' })).toBeChecked()
})

test('a clicked text is auto width, a dragged one a fixed empty box shown while dragging, resizing and shift w or h set the mode and nudging keeps it', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  const field = (name: string) => panel.getByRole('textbox', { name })
  const mode = (name: string) => panel.getByRole('radio', { name })
  const type = async (name: string, v: string) => {
    await field(name).fill(v)
    await field(name).press('Enter')
  }
  await page.keyboard.press('t')
  await page.mouse.click(...(await screen(page, 20, 80)))
  await expect(mode('Auto width')).toBeChecked()
  await expect(field('W in mm')).toHaveValue('0')
  await expect(field('H in mm')).toHaveValue('5.8')
  await expect(panel.getByRole('combobox', { name: 'Width sizing' })).toHaveCount(0)

  await page.keyboard.press('Escape')
  await page.keyboard.press('t')
  const [x0, y0] = await screen(page, 20, 100)
  await page.mouse.move(x0, y0)
  await page.mouse.down()
  await page.mouse.move(...(await screen(page, 60, 120)), { steps: 4 })
  const edge = await pixels(page, x0 - 3, y0 + 20, 6, 1)
  expect(edge.some(([r, g, b]) => b > 200 && r < 100 && g > 100)).toBe(true)
  await page.mouse.up()
  await expect(mode('Fixed size')).toBeChecked()
  await expect(field('W in mm')).toHaveValue('40')
  await expect(field('H in mm')).toHaveValue('20')
  await expect(page.getByRole('textbox', { name: 'Text editor' })).toBeFocused()
  await page.keyboard.type('Hi')
  await expect(page.getByRole('tree', { name: 'Layers' }).getByRole('button', { name: 'Hi', exact: true })).toBeVisible()
  await expect(field('H in mm')).toHaveValue('20')
  await type('H in mm', '30')
  await expect(mode('Fixed size')).toBeChecked()
  await mode('Auto height').click()
  await expect(field('H in mm')).toHaveValue('5.8')
  await mode('Auto width').click()
  await expect(mode('Auto width')).toBeChecked()
  await expect(field('W in mm')).not.toHaveValue('40')
  const w = await field('W in mm').inputValue()
  const x = Number(await field('X in mm').inputValue())
  await page.evaluate(() => (document.activeElement as HTMLElement).blur())
  await page.keyboard.press('Escape')
  await page.keyboard.press('ArrowRight')
  await expect(field('X in mm')).toHaveValue(String(Math.round(x * 10 + 1) / 10))
  await expect(mode('Auto width')).toBeChecked()
  await expect(field('W in mm')).toHaveValue(w)
  await page.keyboard.press('Shift+H')
  await expect(mode('Auto height')).toBeChecked()
  await page.keyboard.press('Shift+W')
  await expect(mode('Auto width')).toBeChecked()
})

test('a fixed text frame pulled narrower than its text becomes auto height', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  await page.keyboard.press('t')
  await drag(page, await screen(page, 20, 100), await screen(page, 120, 110))
  await page.keyboard.type('Satz sets type in the browser')
  await page.keyboard.press('Escape')
  await expect(panel.getByRole('radio', { name: 'Fixed size' })).toBeChecked()
  await drag(page, await screen(page, 120, 105), await screen(page, 50, 105))
  await expect(panel.getByRole('radio', { name: 'Auto height' })).toBeChecked()
  await expect(panel.getByRole('textbox', { name: 'W in mm' })).toHaveValue('30')
  await expect(panel.getByRole('textbox', { name: 'H in mm' })).not.toHaveValue('10')
})

test('a space typed at the end of an auto width text stays on its line', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  const field = (name: string) => panel.getByRole('textbox', { name })
  await page.keyboard.press('t')
  await page.mouse.click(...(await screen(page, 20, 80)))
  await page.keyboard.type('Hello')
  await expect(field('H in mm')).toHaveValue('5.8')
  const w = await field('W in mm').inputValue()
  await page.keyboard.type(' ')
  await expect(field('W in mm')).not.toHaveValue(w)
  await expect(field('H in mm')).toHaveValue('5.8')
})

test('ctrl while resizing a text scales its type, and a new format scales the layers and text, a new width does not', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  const field = (name: string) => panel.getByRole('textbox', { name })
  await page.keyboard.press('t')
  await drag(page, await screen(page, 20, 100), await screen(page, 120, 110))
  await page.keyboard.type('Satz')
  await page.keyboard.press('Escape')
  await field('Font size in pt').fill('10')
  await field('Font size in pt').press('Enter')
  await page.keyboard.down('Control')
  await drag(page, await screen(page, 120, 105), await screen(page, 170, 105))
  await page.keyboard.up('Control')
  await expect(field('W in mm')).toHaveValue('150')
  await expect(field('Font size in pt')).toHaveValue('15')
  await page.keyboard.press('Escape')
  await choose(panel.getByRole('combobox', { name: 'Format', exact: true }), 'A6')
  await page.getByRole('tree', { name: 'Layers' }).getByRole('button', { name: /^Satz$/ }).click()
  await expect(field('X in mm')).toHaveValue('14.19')
  await expect(field('W in mm')).toHaveValue('106.42')
  await expect(field('Font size in pt')).toHaveValue('10.61')
  await page.keyboard.press('Escape')
  await field('Width of all pages in mm').fill('74')
  await field('Width of all pages in mm').press('Enter')
  await page.getByRole('tree', { name: 'Layers' }).getByRole('button', { name: /^Satz$/ }).click()
  await expect(field('X in mm')).toHaveValue('14.19')
  await expect(field('W in mm')).toHaveValue('106.42')
})
