import { expect, test } from '@playwright/test'
import { open, pixels, screen } from './util'

test('type attributes and a text style are set in the text section and edited on the page', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  const text = page.getByRole('tree', { name: 'Layers' }).getByRole('button', { name: /^Satz sets type/ })
  const field = (name: string) => panel.getByRole('textbox', { name })
  const commit = async (name: string, value: string) => {
    await field(name).fill(value)
    await field(name).press('Enter')
  }
  await text.click()
  await expect(field('Font size in pt')).toHaveValue('14')
  await expect(field('Line height in pt')).toHaveValue('Auto')
  await expect(panel.getByRole('radio', { name: 'Justify' })).toBeChecked()

  await commit('Font size in pt', '11')
  await commit('Line height in pt', '15')
  await panel.getByRole('radio', { name: 'Align center' }).click()
  await expect(panel.getByRole('radio', { name: 'Align center' })).toBeChecked()
  await panel.getByRole('button', { name: 'Create text style' }).click()
  await expect(panel.getByRole('combobox', { name: 'Text style' }).locator('option:checked')).toHaveText('Text style 1')

  await page.keyboard.press('Escape')
  const style = panel.getByRole('group', { name: 'Text style 1' })
  await expect(style.getByRole('textbox', { name: 'Font size in pt' })).toHaveValue('11')
  await style.getByRole('textbox', { name: 'Font size in pt' }).fill('9')
  await style.getByRole('textbox', { name: 'Font size in pt' }).press('Enter')
  await text.click()
  await expect(field('Font size in pt')).toHaveValue('9')
  await commit('Line height in pt', 'auto')
  await expect(field('Line height in pt')).toHaveValue('Auto')
  await expect(panel.getByRole('combobox', { name: 'Text style' }).locator('option:checked')).toHaveText('No style')
  await expect(field('Font size in pt')).toHaveValue('9')
})

test('hyphenation is switched per paragraph with its language', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  await page.getByRole('tree', { name: 'Layers' }).getByRole('button', { name: /^Satz sets type/ }).click()
  const hyphenate = panel.getByRole('checkbox', { name: 'Hyphenate' })
  const lang = panel.getByRole('combobox', { name: 'Hyphenation language' })
  await expect(hyphenate).toBeChecked()
  await expect(lang).toHaveValue('en')
  await lang.selectOption('German')
  await hyphenate.uncheck()
  await page.keyboard.press('Control+z')
  await expect(hyphenate).toBeChecked()
  await expect(lang).toHaveValue('de')
})

test('insets, columns, vertical alignment and baseline grid are set in the text frame section', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  await page.getByRole('tree', { name: 'Layers' }).getByRole('button', { name: /^Satz sets type/ }).click()
  const frame = panel.getByRole('region', { name: 'Text frame' })
  const field = (name: string) => frame.getByRole('textbox', { name })
  await expect(field('Columns')).toHaveValue('1')
  await expect(field('Baseline grid in pt')).toHaveValue('Off')
  for (const [name, value] of [['Top inset in mm', '2'], ['Columns', '2'], ['Gutter in mm', '5'], ['Baseline grid in pt', '18']]) {
    await field(name).fill(value)
    await field(name).press('Enter')
  }
  await frame.getByRole('radio', { name: 'Align bottom' }).click()
  await page.keyboard.press('Escape')
  await page.getByRole('tree', { name: 'Layers' }).getByRole('button', { name: /^Satz sets type/ }).click()
  await expect(field('Top inset in mm')).toHaveValue('2')
  await expect(field('Columns')).toHaveValue('2')
  await expect(field('Gutter in mm')).toHaveValue('5')
  await expect(field('Baseline grid in pt')).toHaveValue('18')
  await expect(frame.getByRole('radio', { name: 'Align bottom' })).toBeChecked()
})

test('a clicked text is auto width, a dragged one a fixed empty box shown while dragging, and resizing sets the mode', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  const field = (name: string) => panel.getByRole('textbox', { name })
  const mode = (name: string) => panel.getByRole('radio', { name })
  const type = async (name: string, v: string) => {
    await field(name).fill(v)
    await field(name).press('Enter')
  }
  await page.keyboard.press('t')
  await page.mouse.click(...(await screen(page, 20, 80)))
  await expect(mode('Auto width')).toBeChecked()
  await expect(field('W in mm')).toHaveValue('0')
  await expect(field('H in mm')).toHaveValue('5.8')
  await expect(panel.getByRole('combobox', { name: 'Width sizing' })).toHaveValue('hug')

  await page.keyboard.press('Escape')
  await page.keyboard.press('t')
  const [x0, y0] = await screen(page, 20, 100)
  await page.mouse.move(x0, y0)
  await page.mouse.down()
  await page.mouse.move(...(await screen(page, 60, 120)), { steps: 4 })
  const edge = await pixels(page, x0 - 3, y0 + 20, 6, 1)
  expect(edge.some(([r, g, b]) => b > 200 && r < 100 && g > 100)).toBe(true)
  await page.mouse.up()
  await expect(mode('Fixed size')).toBeChecked()
  await expect(field('W in mm')).toHaveValue('40')
  await expect(field('H in mm')).toHaveValue('20')
  await expect(page.getByRole('textbox', { name: 'Text editor' })).toBeFocused()
  await page.keyboard.type('Hi')
  await expect(page.getByRole('tree', { name: 'Layers' }).getByRole('button', { name: 'Hi', exact: true })).toBeVisible()
  await expect(field('H in mm')).toHaveValue('20')
  await type('H in mm', '30')
  await expect(mode('Fixed size')).toBeChecked()
  await mode('Auto height').click()
  await expect(field('H in mm')).toHaveValue('5.8')
  await panel.getByRole('combobox', { name: 'Width sizing' }).selectOption('Hug')
  await expect(mode('Auto width')).toBeChecked()
  await expect(field('W in mm')).not.toHaveValue('40')
})

test('a space typed at the end of an auto width text stays on its line', async ({ page }) => {
  await open(page)
  const panel = page.getByRole('complementary', { name: 'Properties' })
  const field = (name: string) => panel.getByRole('textbox', { name })
  await page.keyboard.press('t')
  await page.mouse.click(...(await screen(page, 20, 80)))
  await page.keyboard.type('Hello')
  await expect(field('H in mm')).toHaveValue('5.8')
  const w = await field('W in mm').inputValue()
  await page.keyboard.type(' ')
  await expect(field('W in mm')).not.toHaveValue(w)
  await expect(field('H in mm')).toHaveValue('5.8')
})
