import { png, props, rest, select, shot, start, test } from './lib'
import { place, port } from '../e2e/util'

const K = '04 Canvas'
const B = '03 Toolbar'
const STAR = [731, 275] as const
const TRI = [863, 290] as const
const SUN = [596, 273] as const
const TEXT = [700, 560] as const
const EMPTY = [380, 600] as const
const view = () => ({ x: 300, y: 60, width: 1000, height: 940 })
const top = () => ({ x: 400, y: 60, width: 800, height: 420 })

test('selection marks', async ({ page }) => {
  await start(page)
  await page.mouse.move(...STAR)
  await shot(page, K, '01 hover outline', 'Hover outline over a layer', [top()], 0)
  await select(page, 'Star')
  await shot(page, K, '02 selection', 'Selected layer: box, handles, size label, extent on the rulers (whole window)')
  await shot(page, K, '03 selection, close-up', 'Selection handles and quick edit bar, close-up', [top()], 0)
  await select(page, 'Blurred tile')
  await shot(page, K, '04 rectangle radius handles', 'Rectangle with radius handles', [top()], 0)
  await select(page, 'Arrow')
  await shot(page, K, '05 line ends', 'Line with its end handles', [top()], 0)
  await select(page, 'Triangle')
  await props(page).getByRole('textbox', { name: /^Rotation/ }).fill('20')
  await page.keyboard.press('Enter')
  await rest(page)
  await shot(page, K, '06 rotated selection', 'Rotated layer selection', [top()], 0)
  await page.keyboard.press('Control+z')
  await select(page, 'Star', 'Triangle')
  await shot(page, K, '07 multi selection', 'Two layers: union box, outlines, swap circles at the centres', [top()], 0)
  await page.mouse.move(...STAR)
  await page.mouse.down()
  await page.mouse.move(STAR[0] + 10, STAR[1] + 4, { steps: 4 })
  await page.mouse.move(STAR[0] + 20, STAR[1] + 8, { steps: 4 })
  await shot(page, K, '08 dragging selection', 'Dragging two layers', [top()], 0)
  await page.mouse.up()
  await page.keyboard.press('Control+z')
  await page.keyboard.press('Escape')
  await page.locator('.layer-name').filter({ hasText: /^Shapes$/ }).click()
  await rest(page)
  await shot(page, K, '09 group selection', 'Group selected, swap circles of its children', [top()], 0)
  await page.keyboard.press('Escape')
  await page.mouse.move(...EMPTY)
  await page.mouse.down()
  await page.mouse.move(600, 340, { steps: 4 })
  await page.mouse.move(800, 330, { steps: 4 })
  await shot(page, K, '10 marquee', 'Marquee selection in progress', [view()], 0)
  await page.mouse.up()
  await page.keyboard.press('Escape')
})

test('snapping and measuring', async ({ page }) => {
  await start(page)
  await select(page, 'Star')
  await page.mouse.move(...STAR)
  await page.mouse.down()
  await page.mouse.move(STAR[0] + 30, STAR[1] + 40, { steps: 6 })
  await page.mouse.move(STAR[0] + 40, STAR[1] + 3, { steps: 6 })
  await shot(page, K, '11 snap guides', 'Snap guides while moving a layer', [top()], 0)
  await page.mouse.up()
  await page.keyboard.press('Control+z')
  await select(page, 'Star')
  await page.mouse.move(...TRI)
  await page.keyboard.down('Alt')
  await page.mouse.move(TRI[0] + 1, TRI[1])
  await shot(page, K, '12 alt distances', 'Alt held: distances to the hovered layer', [top()], 0)
  await page.mouse.move(700, 700)
  await shot(page, K, '13 alt distances to page', 'Alt held over the page: distances to the page edges', [view()], 0)
  await page.keyboard.up('Alt')
  await page.mouse.move(...STAR)
  await page.mouse.down()
  await page.mouse.move(400, 600, { steps: 8 })
  await shot(page, K, '14 moving off the page', 'Moving a layer onto the pasteboard', [view()], 0)
  await page.mouse.up()
  await page.keyboard.press('Control+z')
})

test('drawing tools', async ({ page }) => {
  await start(page)
  const tools = page.getByRole('toolbar', { name: 'Tools' })
  for (const [k, n] of [['f', 'frame'], ['r', 'rectangle'], ['l', 'line'], ['o', 'ellipse'], ['p', 'pen'], ['t', 'text'], ['i', 'eyedropper']]) {
    await page.keyboard.press(k)
    await rest(page)
    await shot(page, B, `0${['f', 'r', 'l', 'o', 'p', 't', 'i'].indexOf(k) + 2} ${n} tool`, `Toolbar with the ${n} tool active`, [tools], 6)
  }
  await page.keyboard.press('v')
  await rest(page)
  await shot(page, B, '01 move tool', 'Toolbar with the move tool active', [tools], 6)
  await tools.getByRole('button', { name: /Shape tools/ }).click()
  await shot(page, B, '10 shape tools menu', 'Shape tools menu', [tools, page.getByRole('menu')], 12)
  await page.keyboard.press('Escape')
  await page.keyboard.press('r')
  await page.mouse.move(560, 700)
  await page.mouse.down()
  await page.mouse.move(700, 760, { steps: 5 })
  await shot(page, K, '20 drawing a rectangle', 'Drawing a rectangle', [view()], 0)
  await page.mouse.up()
  await rest(page)
  await shot(page, K, '21 new rectangle', 'Rectangle just drawn', [view()], 0)
  await page.keyboard.press('p')
  await page.mouse.click(560, 680)
  await page.mouse.move(640, 640)
  await page.mouse.down()
  await page.mouse.move(700, 620, { steps: 4 })
  await page.mouse.up()
  await page.mouse.move(760, 720)
  await shot(page, K, '22 pen in progress', 'Pen tool: anchors, handles, rubber band', [view()], 0)
  await page.keyboard.press('Escape')
  await page.keyboard.press('Escape')
  await page.keyboard.press('v')
  await select(page, 'Star')
  await page.evaluate(() => (document.activeElement as HTMLElement).blur())
  await page.keyboard.press('Enter')
  await rest(page)
  await shot(page, K, '23 path edit', 'Editing points of a shape', [top()], 0)
  await shot(page, B, '11 path tools', 'Path tools toolbar while editing points', [page.getByRole('toolbar', { name: 'Path tools' })], 6)
  await page.mouse.move(STAR[0], STAR[1] - 62)
  await shot(page, K, '24 path edit, hover point', 'Hovering a point while editing', [top()], 0)
  await page.keyboard.press('Escape')
  await page.keyboard.press('Escape')
  await page.keyboard.press('t')
  await page.mouse.move(560, 650)
  await page.mouse.down()
  await page.mouse.move(800, 760, { steps: 5 })
  await shot(page, K, '25 drawing a text frame', 'Drawing a text frame', [view()], 0)
  await page.mouse.up()
  await page.keyboard.type('New text')
  await shot(page, K, '26 typing in a new frame', 'Typing into a new text frame', [view()], 0)
})

test('text marks', async ({ page }) => {
  await start(page)
  await page.mouse.click(...TEXT)
  await rest(page)
  await shot(page, K, '30 text frame selected', 'Text frame selected: ports', [view()], 0)
  await page.mouse.dblclick(...TEXT)
  await page.mouse.dblclick(...TEXT)
  await shot(page, K, '31 text editing, word selected', 'Editing text with a selected word', [view()], 0)
  await page.keyboard.press('ArrowRight')
  await shot(page, K, '32 text caret', 'Text caret while editing', [view()], 0)
  await page.keyboard.press('Shift+ArrowDown')
  await page.keyboard.press('Shift+ArrowDown')
  await shot(page, K, '33 text selection', 'Text selection over lines', [view()], 0)
  await shot(page, '07 Text', '20 properties while editing text', 'Properties while editing text', ['right'])
  await page.keyboard.press('Escape')
  await page.keyboard.press('Escape')
  await page.mouse.click(...TEXT)
  await props(page).getByRole('textbox', { name: /^H\b/ }).first().fill('15')
  await page.keyboard.press('Enter')
  await rest(page)
  await shot(page, K, '34 overset text', 'Overset text frame: red out-port', [view()], 0)
  const v = async (n: string) => Number(await props(page).getByRole('textbox', { name: new RegExp(`^${n}\\b`) }).first().inputValue())
  const [x, y, w, h] = [await v('X'), await v('Y'), await v('W'), await v('H')]
  await page.mouse.click(...(await port(page, [x, y, x + w, y + h], true)))
  await page.mouse.move(800, 700)
  await shot(page, K, '35 threading', 'Threading from the out-port: loaded cursor', [view()], 0)
  await page.mouse.move(566, 650)
  await page.mouse.down()
  await page.mouse.move(1010, 760, { steps: 5 })
  await page.mouse.up()
  await rest(page)
  await shot(page, K, '36 threaded frames', 'Second frame of a thread selected', [view()], 0)
  await page.mouse.click(700, 505)
  await rest(page)
  await shot(page, K, '37 threaded ports', 'First frame of a thread selected: threaded out-port', [view()], 0)
})

test('grids, guides, wrap', async ({ page }) => {
  await start(page)
  await props(page).getByRole('button', { name: 'Grid presets' }).click()
  await page.getByRole('menu').getByRole('menuitem', { name: '12 columns' }).click()
  await rest(page)
  await shot(page, K, '40 layout grid', 'Layout grid of 12 columns')
  await page.keyboard.press('Control+z')
  await props(page).getByRole('button', { name: 'Grid presets' }).click()
  await page.getByRole('menu').getByRole('menuitem', { name: '5 mm grid' }).click()
  await rest(page)
  await shot(page, K, '41 square grid', 'Square grid of 5 mm', [view()], 0)
  await page.keyboard.press('Control+z')
  await page.mouse.move(800, 50)
  await page.mouse.down()
  await page.mouse.move(800, 300, { steps: 5 })
  await page.mouse.move(800, 450, { steps: 5 })
  await shot(page, K, '42 dragging a guide', 'Dragging a guide out of the ruler')
  await page.mouse.up()
  await page.mouse.move(290, 600)
  await page.mouse.down()
  await page.mouse.move(600, 600, { steps: 5 })
  await page.mouse.up()
  await rest(page)
  await shot(page, K, '43 guides', 'Guides from both rulers')
  await page.mouse.move(800, 450)
  await shot(page, K, '44 guide hover', 'Hovered guide', [view()], 0)
  await select(page, 'Blurred tile')
  await props(page).getByRole('combobox', { name: 'Text wrap' }).click()
  await page.getByRole('menu').getByRole('menuitemradio', { name: 'Wrap around' }).click()
  await props(page).getByRole('textbox', { name: /^Y\b/ }).first().fill('100')
  await page.keyboard.press('Enter')
  await rest(page)
  await shot(page, K, '45 text wrap', 'Text wrapping around a layer above it', [view()], 0)
  await shot(page, P, '30 layer with text wrap', 'Properties of a layer with text wrap', ['right'])
})

const P = '05 Properties'

test('auto layout marks', async ({ page }) => {
  await start(page)
  await select(page, 'Sun', 'Star', 'Triangle')
  await page.keyboard.press('Shift+a')
  await rest(page)
  await shot(page, K, '50 auto layout row', 'Auto layout row selected: padding and gap handles', [top()], 0)
  const tri = (await page.locator('.quick').boundingBox())!
  void tri
  await page.mouse.dblclick(...SUN)
  await rest(page)
  await page.mouse.move(...SUN)
  await page.mouse.down()
  await page.mouse.move(SUN[0] + 100, SUN[1], { steps: 5 })
  await page.mouse.move(SUN[0] + 200, SUN[1] + 5, { steps: 5 })
  await shot(page, K, '51 auto layout insert line', 'Moving a child inside auto layout: insert line', [top()], 0)
  await page.mouse.up()
})

test('place image', async ({ page }) => {
  await start(page)
  const chooser = page.waitForEvent('filechooser')
  await page.getByRole('button', { name: 'Place image' }).click()
  await (await chooser).setFiles(png('photo.png', 300, 200, (x, y) => [x % 256, y, 160]))
  await page.mouse.move(700, 700)
  await shot(page, K, '60 placing an image', 'Placing an image: preview at the pointer', [view()], 0)
  await page.mouse.click(700, 700)
  await rest(page)
  await shot(page, K, '61 placed image', 'Placed image selected', [view()], 0)
  void place
})
