import { example, expect, layers, opened, png, props, rest, select, shot, start, test } from './lib'
import { place } from '../e2e/util'

const G = '09 Pages & masters'
const L = '08 Layers & swatches'
const F = '10 Preflight & export'
const ov = (page) => page.getByRole('region', { name: 'Page overview' })
const sw = (page) => page.getByRole('navigation', { name: 'Spreads' })

test('overview', async ({ page }) => {
  await example(page, 'booklet.satz')
  await shot(page, G, '01 switcher, first page', 'Spread switcher on the first page', [sw(page)], 8)
  await page.keyboard.press('PageDown')
  await rest(page)
  await shot(page, G, '02 switcher, a spread', 'Spread switcher on a spread', [sw(page)], 8)
  await page.keyboard.press('End')
  await rest(page)
  await shot(page, G, '03 switcher, last spread', 'Last spread: Add page instead of next', [sw(page)], 8)
  await page.keyboard.press('Home')
  await page.keyboard.press('.')
  await rest(page)
  await shot(page, G, '10 page overview', 'Page overview (.) with masters and spreads')
  const pages = ov(page).getByRole('listbox', { name: 'Pages' })
  await pages.getByRole('option', { name: 'Page 3', exact: true }).click({ modifiers: ['Control'] }).catch(() => {})
  await pages.getByRole('option', { name: 'Page 4', exact: true }).click({ modifiers: ['Shift'] })
  await rest(page)
  await shot(page, G, '11 page overview, selection', 'Pages selected in the overview')
  await pages.getByRole('option', { name: 'Page 4', exact: true }).click({ button: 'right' })
  await shot(page, G, '12 page context menu', 'Page context menu', [pages.getByRole('option', { name: 'Page 4', exact: true }), page.getByRole('menu')], 16)
  await page.keyboard.press('Escape')
  const masters = ov(page).getByRole('listbox', { name: 'Masters' })
  await masters.getByRole('option').first().click({ button: 'right' })
  await shot(page, G, '13 master context menu', 'Master context menu', [masters.getByRole('option').first(), page.getByRole('menu')], 16)
  await page.keyboard.press('Escape')
  const box = (await pages.getByRole('option', { name: 'Page 5', exact: true }).boundingBox())!
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down()
  await page.mouse.move(box.x + box.width / 2 + 20, box.y + 10, { steps: 4 })
  await page.mouse.move(box.x - 10, box.y - box.height / 2, { steps: 6 })
  await shot(page, G, '14 dragging a page', 'Dragging a page: drop indicator')
  await page.keyboard.press('Escape')
  await page.mouse.up()
  await page.keyboard.press('Control+z').catch(() => {})
  const ob = (await ov(page).boundingBox())!
  await page.mouse.move(ob.x + ob.width - 40, ob.y + ob.height - 40)
  await page.mouse.down()
  await page.mouse.move(ob.x + ob.width - 300, ob.y + ob.height - 400, { steps: 6 })
  await shot(page, G, '15 overview marquee', 'Marquee band in the page overview')
  await page.mouse.up()
  await ov(page).getByRole('spinbutton', { name: 'Columns' }).or(ov(page).getByRole('textbox', { name: 'Columns' })).fill('3')
  await page.keyboard.press('Enter')
  await rest(page)
  await shot(page, G, '16 overview, 3 columns', 'Page overview with 3 columns of spreads')
  await masters.getByRole('option').first().click({ button: 'right' })
  await page.getByRole('menu').getByRole('menuitem', { name: 'Rename' }).click()
  await shot(page, G, '17 master rename', 'Master being renamed', [masters], 8)
  await page.keyboard.press('Escape')
  await shot(page, G, '18 masters column', 'Masters column', [masters], 8)
})

test('master editing', async ({ page }) => {
  await example(page, 'booklet.satz')
  await page.keyboard.press('PageDown')
  await rest(page)
  await shot(page, G, '20 page with a master, properties', 'Page properties of a page with a master', ['right'])
  await page.keyboard.press('.')
  await ov(page).getByRole('listbox', { name: 'Masters' }).getByRole('option').first().click()
  await rest(page)
  await shot(page, G, '21 editing a master', 'Editing a master: banner, switcher shows the master')
  await shot(page, G, '22 master banner', 'Master banner', [page.locator('.master-banner, [class*=banner]').first()], 16)
  await shot(page, G, '23 master properties', 'Properties of an open master', ['right'])
  await shot(page, L, '05 layers of a master', 'Layers of a master', ['left'])
  await page.keyboard.press('Escape')
  await rest(page)
  await shot(page, L, '06 layers of a page with master', 'Layers of a page with master layers', ['left'])
})

test('layers', async ({ page }) => {
  await start(page)
  await shot(page, L, '01 layers', 'Layers tree', ['left'])
  const row = (n: string) => layers(page).getByRole('treeitem', { name: n }).first()
  await select(page, 'Star')
  await row('Star').hover()
  await shot(page, L, '02 layer hover and selected', 'Selected row and the hover actions (lock, eye)', ['left'])
  await row('Triangle').hover()
  await row('Triangle').getByRole('button', { name: 'Hide' }).click()
  await row('Sun').hover()
  await row('Sun').getByRole('button', { name: 'Lock' }).click()
  await select(page, 'Arrow', 'Blurred tile')
  await shot(page, L, '03 hidden, locked, multi selection', 'Hidden layer (Triangle), locked layer (Sun), several selected', ['left'])
  await shot(page, '04 Canvas', '70 hidden and locked layers', 'Canvas with a hidden and a locked layer')
  await layers(page).locator('.layer-name').filter({ hasText: /^Arrow$/ }).dblclick()
  await shot(page, L, '04 layer rename', 'Layer being renamed', ['left'])
  await page.keyboard.press('Escape')
  const from = (await layers(page).locator('.layer-name').filter({ hasText: /^Star$/ }).boundingBox())!
  const to = (await layers(page).locator('.layer-name').filter({ hasText: /^Frame$/ }).boundingBox())!
  await page.mouse.move(from.x + 10, from.y + 5)
  await page.mouse.down()
  await page.mouse.move(to.x + 10, to.y + 2, { steps: 6 })
  await shot(page, L, '07 drag, drop above', 'Dragging a layer: drop above', ['left'])
  await page.mouse.move(to.x + 10, to.y + to.height / 2, { steps: 3 })
  await shot(page, L, '08 drag, drop into', 'Dragging a layer: drop into a frame', ['left'])
  await page.keyboard.press('Escape')
  await page.mouse.up()
  await page.keyboard.press('Control+z')
  await layers(page).getByRole('button', { name: 'Collapse' }).first().click()
  await rest(page)
  await shot(page, L, '09 collapsed group', 'Collapsed group', ['left'])
  await layers(page).locator('.layer-name').filter({ hasText: /^Frame$/ }).click({ button: 'right' })
  await shot(page, L, '10 layer context menu', 'Context menu on a layer row', ['left', page.getByRole('menu')], 0)
})

test('layers of a spread', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('satz.settings', JSON.stringify({ layers: 'spread' })))
  await example(page, 'booklet.satz')
  await page.keyboard.press('PageDown')
  await rest(page)
  await shot(page, L, '11 layers of a spread', 'Layers of the spread (setting), with page headers', ['left'])
})

test('preflight rgb', async ({ page }) => {
  await start(page, { h: 1200 })
  await page.keyboard.press('Control+Alt+y')
  await rest(page)
  const pf = page.getByRole('region', { name: 'Preflight' })
  await shot(page, F, '01 preflight, no issues', 'Preflight without issues (RGB)')
  await shot(page, F, '02 preflight panel, no issues', 'Preflight panel without issues', ['right'])
  await opened(page, F, '03 format select', 'Export format select', pf.getByRole('combobox', { name: 'Format' }))
  await opened(page, F, '04 preset select', 'Preset select in an RGB document (X-1a disabled)', pf.getByRole('combobox', { name: 'Preset' }))
  for (const [i, f] of [['05', 'PNG'], ['06', 'JPEG'], ['07', 'Package']] as const) {
    await pf.getByRole('combobox', { name: 'Format' }).click()
    await page.getByRole('menu').getByRole('menuitemradio', { name: new RegExp(`^${f}`) }).click()
    await rest(page)
    await shot(page, F, `${i} export as ${f}`, `Export section for ${f}`, [pf.getByRole('region', { name: 'Export' })], 8)
  }
  await pf.getByRole('textbox', { name: 'Pages to export' }).fill('7-x')
  await shot(page, F, '08 invalid page range', 'Invalid page range disables the export', [pf.getByRole('region', { name: 'Export' })], 8)
  await page.keyboard.press('Escape')
  await page.keyboard.press('Control+Alt+y')
  await select(page, 'Satz sets type…')
  await props(page).getByRole('textbox', { name: /^H\b/ }).first().fill('15')
  await page.keyboard.press('Enter')
  await place(page, png('small.png', 20, 20, (x, y) => [x * 10, y * 10, 80]), [74, 150])
  await props(page).getByRole('textbox', { name: /^W\b/ }).first().fill('80')
  await page.keyboard.press('Enter')
  await page.keyboard.press('Escape')
  await rest(page)
  await shot(page, F, '10 preflight button with errors', 'Top bar preflight count with errors', [page.locator('header.bar .end')], 8)
  await page.keyboard.press('Control+Alt+y')
  await rest(page)
  await shot(page, F, '11 preflight with issues', 'Preflight with errors and warnings')
  await shot(page, F, '12 preflight panel with issues', 'Preflight panel with issues', ['right'])
  await pf.locator('.iss').first().click()
  await rest(page)
  await shot(page, F, '13 issue selected', 'An issue clicked: its layer selected and shown')
})

test('preflight cmyk', async ({ page }) => {
  await example(page, 'poster.satz', { h: 1200 })
  await page.keyboard.press('Control+Alt+y')
  await page.keyboard.press('Shift+1')
  await rest(page)
  const pf = page.getByRole('region', { name: 'Preflight' })
  await expect(pf.getByText('Highest')).toBeVisible()
  await page.waitForTimeout(1500)
  await shot(page, F, '20 preflight CMYK', 'Preflight of a CMYK document: proof, separations, ink coverage')
  await shot(page, F, '21 preflight CMYK panel', 'Preflight panel (CMYK)', ['right'])
  await pf.getByRole('checkbox', { name: 'Mark colours outside the gamut' }).check()
  await page.waitForTimeout(1500)
  await shot(page, F, '22 gamut marks', 'Colours outside the gamut marked on the canvas')
  await pf.getByRole('checkbox', { name: 'Mark colours outside the gamut' }).check()
  await pf.getByText('Mark above limit').click()
  await pf.getByRole('textbox', { name: 'Ink limit' }).fill('200')
  await page.keyboard.press('Enter')
  await page.waitForTimeout(1500)
  await shot(page, F, '23 ink above limit', 'Ink above the limit marked on the canvas')
  await pf.getByText('Mark above limit').click()
  const plates = pf.getByRole('region', { name: 'Separations' }).locator('.plate')
  await plates.first().click()
  await page.waitForTimeout(1500)
  await shot(page, F, '24 cyan plate off', 'Separations with the cyan plate turned off')
  await plates.first().click()
  await plates.last().click()
  await page.waitForTimeout(1500)
  await shot(page, F, '25 cyan and spot plates off', 'Separations with the cyan and the spot plate turned off')
  await plates.last().click()
  const c = (await page.getByLabel('Page canvas').boundingBox())!
  await page.mouse.move(c.x + c.width / 2, c.y + c.height * 0.55)
  await page.waitForTimeout(800)
  await shot(page, F, '26 ink under pointer', 'Ink coverage under the pointer', [pf.getByRole('region', { name: 'Ink coverage' })], 8)
  await rest(page)
  await opened(page, F, '27 preset select CMYK', 'Preset select in a CMYK document', pf.getByRole('combobox', { name: 'Preset' }))
  await pf.locator('.pf-go').click()
  await shot(page, F, '28 exporting', 'Exporting: button and progress bar', [pf.getByRole('region', { name: 'Export' })], 8)
  await page.waitForTimeout(5000)
  await shot(page, F, '29 exported', 'After the export: status line', [page.locator('.status'), pf.getByRole('region', { name: 'Export' })], 8)
})
