import { opened, props, rest, section, select, shot, start, test } from './lib'

const C = '06 Popovers & menus'
const T = '07 Text'
const combo = (page, name: string | RegExp) => props(page).getByRole('combobox', { name }).first()

test('color pickers and selects', async ({ page }) => {
  await start(page, { h: 1400 })
  await select(page, 'Rectangle')
  const fill = section(page, 'Fill')
  const pick = page.getByRole('dialog', { name: 'Fill color' })
  await opened(page, C, '01 color picker, RGB', 'Colour picker (RGB): SV area, hue, alpha, hex', fill.getByRole('button', { name: 'Fill color' }).first(), pick)
  await fill.getByRole('button', { name: 'Fill color' }).first().click()
  await pick.getByRole('tab', { name: 'Swatches' }).click()
  await shot(page, C, '02 color picker, swatches tab empty', 'Swatches tab without swatches or variables', [fill, pick], 16)
  await page.keyboard.press('Escape')
  await opened(page, C, '03 fill type select', 'Paint type select (Solid, Linear, Radial)', fill.getByRole('combobox').first())
  await opened(page, C, '04 blend mode select', 'Blend mode select', combo(page, 'Blend mode'))
  await opened(page, C, '05 text wrap select', 'Text wrap select', combo(page, 'Text wrap'))
  await opened(page, C, '06 constraints select', 'Constraint select (inside a frame)', section(page, 'Layout').getByRole('combobox').first())
  await section(page, 'Stroke').getByRole('button', { name: 'Add stroke' }).click()
  await rest(page)
  await shot(page, C, '07 stroke added', 'Stroke section after adding a stroke', [section(page, 'Stroke')], 8)
  await section(page, 'Stroke').getByText('Each side').click()
  await shot(page, C, '08 stroke each side', 'Stroke with Each side (T, R, B, L)', [section(page, 'Stroke')], 8)
  await opened(page, C, '09 line style select', 'Line style select', combo(page, 'Line style'))
  await section(page, 'Effects').getByRole('button', { name: 'Add effect' }).click()
  await rest(page)
  await shot(page, C, '10 effect drop shadow', 'Effects with a drop shadow', [section(page, 'Effects')], 8)
  await opened(page, C, '11 effect type select', 'Effect type select', combo(page, 'Effect type'))
  await opened(page, C, '12 shadow color', 'Shadow colour picker (no swatch tab)', section(page, 'Effects').getByRole('button', { name: 'Shadow color' }), page.getByRole('dialog', { name: 'Shadow color' }))
  await select(page, 'Sun')
  await shot(page, C, '13 gradient stops', 'Radial gradient with stops', [section(page, 'Fill')], 8)
  await opened(page, C, '14 gradient stop picker', 'Colour picker of a gradient stop', section(page, 'Fill').getByRole('button').filter({ has: page.locator('.chip') }).nth(1), page.getByRole('dialog').last())
  await select(page, 'Arrow')
  await select(page, 'Frame')
  await page.keyboard.press('Shift+a')
  await rest(page)
  await opened(page, C, '16 sizing select', 'Sizing select (Fixed, Hug, Fill)', section(page, 'Layout').getByRole('combobox').first())
  await shot(page, C, '17 auto layout section', 'Auto layout section: direction, alignment, gap, padding', [section(page, 'Auto layout')], 8)
  await opened(page, C, '18 spacing mode select', 'Spacing mode select', combo(page, 'Spacing mode'))
})

test('document and page selects', async ({ page }) => {
  await start(page, { h: 1400 })
  await opened(page, C, '20 page format select', 'Document format select', section(page, 'Document').getByRole('combobox').first())
  await opened(page, C, '21 spreads select', 'Spreads select', combo(page, 'Spreads'))
  await opened(page, C, '22 color mode select', 'Colour mode select', combo(page, 'Color mode'))
  await opened(page, C, '23 master select', 'Master select of a page', combo(page, 'Master'))
  await props(page).getByText('Start section').click()
  await shot(page, C, '24 start section', 'Page starting a section (start, numbering, prefix)', ['right'])
  await opened(page, C, '25 numbering select', 'Numbering select', combo(page, 'Numbering'))
  await opened(page, C, '26 grid presets', 'Layout grid presets', props(page).getByRole('button', { name: 'Grid presets' }))
  await section(page, 'Layout grids').getByRole('button', { name: 'Add layout grid' }).click()
  await rest(page)
  await shot(page, C, '27 layout grid', 'Layout grid row (columns)', [section(page, 'Layout grids')], 8)
  await opened(page, C, '28 grid type select', 'Grid type select', combo(page, 'Grid type'))
  await opened(page, C, '29 variable kinds', 'Create variable menu', section(page, 'Variables').getByRole('button', { name: 'Add variable' }))
  await section(page, 'Variables').getByRole('button', { name: 'Add variable' }).click()
  await page.getByRole('menu', { name: 'Create variable' }).getByRole('menuitem', { name: 'Color' }).click()
  const edit = page.getByRole('dialog', { name: /^Edit / })
  await shot(page, C, '30 variable editor', 'Variable editor popover (modes)', [section(page, 'Variables'), edit], 16)
  await edit.getByRole('button', { name: /Add mode/ }).click().catch(() => {})
  await shot(page, C, '31 variable editor, two modes', 'Variable editor with a second mode', [section(page, 'Variables'), edit], 16)
  await page.keyboard.press('Escape')
  await rest(page)
  await shot(page, C, '32 variables section', 'Variables section with a colour variable and mode selects', ['right'])
  await section(page, 'Variables').getByRole('button').filter({ hasText: /Color|Variable/ }).first().click({ button: 'right' }).catch(() => {})
  if (await page.getByRole('menu', { name: 'Variable' }).count()) {
    await shot(page, C, '33 variable context menu', 'Variable row context menu', [section(page, 'Variables'), page.getByRole('menu')], 16)
    await page.keyboard.press('Escape')
  }
  await select(page, 'Rectangle')
  const bind = props(page).locator('.bind-button').first()
  await opened(page, C, '34 apply variable', 'Apply variable listbox', bind, page.getByRole('listbox').last())
  await section(page, 'Fill').getByRole('button', { name: 'Fill color' }).first().click()
  await page.getByRole('dialog', { name: 'Fill color' }).getByRole('tab', { name: 'Swatches' }).click()
  await shot(page, C, '35 swatches tab with variable', 'Swatches tab listing a colour variable', [section(page, 'Fill'), page.getByRole('dialog', { name: 'Fill color' })], 16)
  await page.getByRole('dialog', { name: 'Fill color' }).getByRole('option').first().click()
  await page.keyboard.press('Escape')
  await rest(page)
  await shot(page, C, '36 fill bound to variable', 'Fill bound to a colour variable', [section(page, 'Fill')], 8)
})

test('cmyk and swatches', async ({ page }) => {
  const { example } = await import('./lib')
  await example(page, 'poster.satz', { h: 1400 })
  await opened(page, C, '40 profile select', 'Output profile select (CMYK)', combo(page, 'Profile'))
  await shot(page, '08 Layers & swatches', '20 swatches panel', 'Swatches panel with a spot colour', [page.getByRole('region', { name: 'Swatches' })], 8)
  const sw = page.getByRole('region', { name: 'Swatches' }).getByRole('option').first()
  await sw.click({ button: 'right' })
  await shot(page, '08 Layers & swatches', '21 swatch context menu', 'Swatch context menu', [sw, page.getByRole('menu')], 16)
  await page.keyboard.press('Escape')
  await sw.dblclick()
  await rest(page)
  await shot(page, '08 Layers & swatches', '22 swatch rename', 'Swatch being renamed', [page.getByRole('region', { name: 'Swatches' })], 8)
  await page.keyboard.press('Escape')
  await page.getByRole('region', { name: 'Swatches' }).getByRole('button', { name: 'Add swatch' }).click()
  const ed = page.getByRole('dialog').last()
  await shot(page, '08 Layers & swatches', '23 edit swatch', 'Edit swatch popover (name, spot, CMYK)', [page.getByRole('region', { name: 'Swatches' }), ed], 16)
  await page.keyboard.press('Escape')
  await rest(page)
  await page.getByRole('tree', { name: 'Layers' }).locator('.layer-name').filter({ hasText: /^Title/ }).first().click()
  await rest(page)
  await shot(page, C, '41 text with spot colour', 'Text bound to a spot swatch (tint)', ['right'])
  await page.getByRole('tree', { name: 'Layers' }).locator('.layer-name').filter({ hasText: /^Sky|^Background/ }).first().click()
  await rest(page)
  const fill = section(page, 'Fill')
  await opened(page, C, '42 color picker, CMYK', 'Colour picker in a CMYK document (C, M, Y, K)', fill.getByRole('button', { name: 'Fill color' }).first(), page.getByRole('dialog', { name: 'Fill color' }))
  await fill.getByRole('button', { name: 'Fill color' }).first().click()
  await page.getByRole('dialog', { name: 'Fill color' }).getByRole('tab', { name: 'Swatches' }).click()
  await shot(page, C, '43 swatches tab CMYK', 'Swatches tab with process and spot swatches', [fill, page.getByRole('dialog', { name: 'Fill color' })], 16)
})

test('text', async ({ page }) => {
  await start(page, { h: 1600 })
  await select(page, 'Satz sets type…')
  await opened(page, T, '01 text styles menu', 'Text style menu', props(page).getByTitle('Text style'))
  await opened(page, T, '02 font select', 'Font select', combo(page, 'Font'))
  await opened(page, T, '04 insert character', 'Insert character menu', props(page).getByRole('button', { name: 'Insert character' }))
  await opened(page, T, '05 type options', 'Type options popover', props(page).getByRole('button', { name: 'Type options' }), page.getByRole('dialog', { name: 'Type options' }))
  await select(page, 'Satz sets type…')
  await opened(page, T, '06 hyphenation language', 'Hyphenation language select', combo(page, 'Hyphenation language'))
  await props(page).getByRole('textbox', { name: 'Columns' }).fill('2')
  await page.keyboard.press('Enter')
  await rest(page)
  await shot(page, T, '08 two columns', 'Text frame with 2 columns and the column rule', [props(page).getByRole('region', { name: 'Text frame' })], 8)
  await shot(page, T, '09 two columns, canvas', 'Two columns on the canvas')
  await props(page).getByTitle('Text style').click()
  await page.getByRole('menu').getByRole('menuitem', { name: /Create text style/ }).click()
  await rest(page)
  await shot(page, T, '11 text style created', 'Text styles section after Create text style', ['right'])
})
