import { example, expect, rest, select, shot, start, test } from './lib'

const A = '01 App shell'
const D = '02 Dialogs'

test('start dialog', async ({ page }) => {
  await start(page, { doc: null })
  const d = page.getByRole('dialog', { name: 'New document' })
  await shot(page, D, '01 new document, first launch', 'New document dialog on first launch (Esc opens the booklet)')
  await shot(page, D, '02 new document, close-up', 'New document dialog, close-up', [d])
  await d.getByText('Custom', { exact: true }).click()
  await shot(page, D, '03 new document, custom format', 'Custom format with W and H fields', [d])
  await page.keyboard.press('Enter')
  await expect(d).toHaveCount(0)
  await rest(page)
  await shot(page, A, '02 new A4 document with status', 'Fresh 8 page custom document, status line "Created …" bottom')
  await page.keyboard.press('Control+Alt+n')
  await shot(page, D, '05 new document from a document', 'New document opened from a document (Esc returns)', [page.getByRole('dialog', { name: 'New document' })])
})

test('shell states', async ({ page }) => {
  await start(page)
  await shot(page, A, '01 app, nothing selected', 'Whole app with the sample, nothing selected')
  await page.keyboard.press('Alt+1')
  await rest(page)
  await shot(page, A, '03 left panel hidden', 'Left panel hidden (Alt+1)')
  await page.keyboard.press('Alt+2')
  await shot(page, A, '04 both panels hidden', 'Both panels hidden (Alt+1, Alt+2)')
  await page.keyboard.press('Alt+1')
  await shot(page, A, '05 right panel hidden', 'Right panel hidden (Alt+2)')
  await page.keyboard.press('Alt+2')
  await page.keyboard.press('Shift+w')
  await shot(page, A, '06 UI hidden', 'Whole UI hidden (Shift+W)')
  await page.keyboard.press('Shift+w')
  await page.keyboard.press('Shift+r')
  await shot(page, A, '07 rulers hidden', 'Rulers hidden (Shift+R)')
  await page.keyboard.press('Shift+r')
  await page.locator('.brand').dblclick()
  await shot(page, A, '08 document rename', 'Document name being renamed (double-click on the name)', [page.locator('.brand')], 40)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Export', exact: true }).hover()
  await page.waitForTimeout(800)
  await shot(page, A, '09 tooltip', 'Tooltip after 500 ms hover', [page.locator('header.bar .end')], 50)
  await page.getByRole('toolbar', { name: 'Tools' }).getByRole('button').first().hover()
  await page.waitForTimeout(800)
  await shot(page, A, '10 tooltip on a tool', 'Tool tooltip with its shortcut', [page.getByRole('toolbar', { name: 'Tools' })], 50)
  await rest(page)
  await shot(page, A, '11 top bar', 'Top bar', [page.locator('header.bar')], 0)
})

test('dialogs', async ({ page }) => {
  await start(page)
  await page.keyboard.press('?')
  const help = page.getByRole('dialog', { name: 'Keyboard shortcuts' })
  await shot(page, D, '10 keyboard shortcuts', 'Keyboard shortcuts (?)')
  await help.getByRole('textbox', { name: 'Search shortcuts' }).fill('zoom')
  await shot(page, D, '11 keyboard shortcuts, search', 'Shortcuts filtered by a search', [help])
  await help.getByRole('textbox', { name: 'Search shortcuts' }).fill('xyzzy')
  await shot(page, D, '12 keyboard shortcuts, no match', 'No shortcut matches', [help])
  await help.getByRole('textbox', { name: 'Search shortcuts' }).fill('')
  await help.getByRole('button', { name: /^Shortcut for / }).first().click()
  await shot(page, D, '13 keyboard shortcuts, recording', 'Recording a new shortcut ("Press keys")', [help])
  await page.keyboard.press('Control+Alt+j')
  await shot(page, D, '14 keyboard shortcuts, remapped', 'A remapped shortcut shows Reset shortcuts', [help])
  await page.keyboard.press('Escape')
  await page.keyboard.press('Escape')
  await page.keyboard.press('Control+,')
  const settings = page.getByRole('dialog', { name: 'Settings' })
  await shot(page, D, '20 settings', 'Settings (Ctrl+,)')
  await shot(page, D, '21 settings, close-up', 'Settings, close-up', [settings])
  await page.keyboard.press('Escape')
  await page.keyboard.press('Control+k')
  const pal = page.getByRole('dialog', { name: 'Command palette' })
  await shot(page, D, '30 command palette', 'Command palette (Ctrl+K)')
  await pal.getByRole('combobox').or(pal.getByRole('textbox')).first().fill('st')
  await shot(page, D, '31 command palette, search', 'Palette search across commands, layers, pages, swatches', [pal])
  await pal.getByRole('combobox').or(pal.getByRole('textbox')).first().fill('xyzzy')
  await shot(page, D, '32 command palette, nothing', 'Palette with nothing matching', [pal])
  await page.keyboard.press('Escape')
  await page.keyboard.press('Control+f')
  const find = page.getByRole('dialog', { name: 'Find and replace' }).or(page.getByRole('search', { name: 'Find and replace' })).or(page.getByLabel('Find and replace'))
  await shot(page, D, '40 find', 'Find and replace (Ctrl+F)')
  await page.getByRole('textbox', { name: 'Find', exact: true }).fill('the')
  await shot(page, D, '41 find, matches', 'Find with matches highlighted on the canvas')
  await shot(page, D, '42 find, close-up', 'Find and replace, close-up', [find.first()], 24)
  await page.getByRole('textbox', { name: 'Find', exact: true }).fill('xyzzy')
  await shot(page, D, '43 find, no match', 'Find with no match', [find.first()], 24)
})

test('menus', async ({ page }) => {
  await start(page)
  const canvas = page.getByLabel('Page canvas')
  const b = (await canvas.boundingBox())!
  await page.mouse.click(b.x + 60, b.y + 300, { button: 'right' })
  await shot(page, '11 Menus', '01 context menu, nothing selected', 'Context menu on the empty canvas', [page.getByRole('menu')], 40)
  await page.keyboard.press('Escape')
  await select(page, 'Star')
  const star = (await page.locator('.quick').boundingBox())!
  await page.mouse.click(star.x + star.width / 2, star.y + star.height + 60, { button: 'right' })
  await shot(page, '11 Menus', '02 context menu, selection', 'Context menu with a selection', [page.getByRole('menu')], 40)
  await shot(page, '11 Menus', '03 context menu, selection, in context', 'Context menu with a selection, whole window')
})

test('booklet', async ({ page }) => {
  await example(page, 'booklet.satz')
  await shot(page, A, '20 booklet example', 'Booklet example (A5 facing pages, masters)')
  await page.keyboard.press('PageDown')
  await rest(page)
  await shot(page, A, '21 booklet, a spread', 'Booklet showing a spread')
})

test('poster', async ({ page }) => {
  await example(page, 'poster.satz')
  await shot(page, A, '22 poster example', 'Poster example (A2, CMYK, spot colour)')
})
